######################################################################
#
# File name : board_simulate.do
# Created on: Thu Sep 03 16:23:10 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -t 1ps -lib xil_defaultlib board_opt

do {board_wave.do}

view wave
view structure
view signals

do {board.udo}

run 1000ns
