######################################################################
#
# File name : board_elaborate.do
# Created on: Thu Sep 03 16:22:28 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -L gtwizard_ultrascale_v1_5 -work xil_defaultlib xil_defaultlib.board xil_defaultlib.glbl -o board_opt

quit -force
