######################################################################
#
# File name : board_wave.do
# Created on: Thu Jul 16 15:48:23 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
