######################################################################
#
# File name : board_wave.do
# Created on: Tue Jun 30 14:52:47 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
