######################################################################
#
# File name : board_wave.do
# Created on: Thu Sep 03 16:23:10 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
