######################################################################
#
# File name : board_elaborate.do
# Created on: Thu Jul 16 15:48:21 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################

quit -force
