######################################################################
#
# File name : eth_core_tb_compile.do
# Created on: Wed Nov 04 11:57:38 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
file delete -force -- work
file delete -force -- msim

#vlib work
#vlib msim
#
#vlib msim/fifo_generator_v13_0_0
#vlib msim/xil_defaultlib
#
#vmap fifo_generator_v13_0_0 msim/fifo_generator_v13_0_0
#vmap xil_defaultlib msim/xil_defaultlib
#
#vcom -64 -93 -work fifo_generator_v13_0_0 "../../../../sim/testbanch/fifo_ust_ibufrx_example/fifo_ust_ibufrx_example.ip_user_files/ipstatic/fifo_generator_v13_0_0/simulation/fifo_generator_vhdl_beh.vhd"
#vcom -64 -93 -work fifo_generator_v13_0_0 "../../../../sim/testbanch/fifo_ust_ibufrx_example/fifo_ust_ibufrx_example.ip_user_files/ipstatic/fifo_generator_v13_0_0/hdl/fifo_generator_v13_0_rfs.vhd"
#vcom -64 -93 -work fifo_generator_v13_0_0 "../../../../sim/testbanch/fifo_ust_ibufrx_example/fifo_ust_ibufrx_example.srcs/sources_1/ip/fifo_ust_ibufrx/sim/fifo_ust_ibufrx.vhd"
#
#vcom -64 -93 -work xil_defaultlib "../../../lib/reduce_pack.vhd";
#vcom -64 -93 -work xil_defaultlib "../../../lib/vicg_common_pkg.vhd" ;
#vcom -64 -93 -work xil_defaultlib "../../ust_def.vhd";
#vcom -64 -93 -work xil_defaultlib "../../rx_if.vhd"
#
#vcom -64 -93 -work xil_defaultlib "../testbanch/rx_if_tb.vhd";
#
### compile glbl module
##vlog -64 -93 -work xil_defaultlib "glbl.v";
#
#vsim -t 1ps -L xil_defaultlib -L fifo_generator_v13_0_0 -lib xil_defaultlib xil_defaultlib.rx_if_tb

vlib work
vlib msim

vlib msim/fifo_generator_v13_0_0

vmap fifo_generator_v13_0_0 msim/fifo_generator_v13_0_0

vcom -64 -93 -work fifo_generator_v13_0_0 "../../../../sim/testbanch/fifo_ust_ibufrx_example/fifo_ust_ibufrx_example.ip_user_files/ipstatic/fifo_generator_v13_0_0/simulation/fifo_generator_vhdl_beh.vhd"
vcom -64 -93 -work fifo_generator_v13_0_0 "../../../../sim/testbanch/fifo_ust_ibufrx_example/fifo_ust_ibufrx_example.ip_user_files/ipstatic/fifo_generator_v13_0_0/hdl/fifo_generator_v13_0_rfs.vhd"
vcom -64 -93 -work fifo_generator_v13_0_0 "../../../../sim/testbanch/fifo_ust_ibufrx_example/fifo_ust_ibufrx_example.srcs/sources_1/ip/fifo_ust_ibufrx/sim/fifo_ust_ibufrx.vhd"

vcom -64 -93 "../../../lib/reduce_pack.vhd";
vcom -64 -93 "../../../lib/vicg_common_pkg.vhd" ;
vcom -64 -93 "../../ust_def.vhd";
vcom -64 -93 "../../rx_if.vhd"

vcom -64 -93 "../testbanch/rx_if_tb.vhd";

## compile glbl module
#vlog -64 -93 -work xil_defaultlib "glbl.v";

vsim -t 1ps -L fifo_generator_v13_0_0 -lib work rx_if_tb

do rx_if_tb_wave.do
view wave
view structure
view signals
run 4000ns

#quit -force

