######################################################################
#
# File name : eth_core_tb_compile.do
# Created on: Wed Nov 04 11:57:38 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
file delete -force -- work
file delete -force -- msim

vlib work
vlib msim

#vlib msim/fifo_generator_v13_1_0
#vlib msim/blk_mem_gen_v8_3_2
#
#vmap fifo_generator_v13_1_0 msim/fifo_generator_v13_1_0
#vmap blk_mem_gen_v8_3_2 msim/blk_mem_gen_v8_3_2

#vlog -64  -work fifo_generator_v13_1_0 "../../../../sim/testbanch/fifo_rqrd_example/fifo_rqrd_example.ip_user_files/ipstatic/fifo_generator_v13_1_0/simulation/fifo_generator_vlog_beh.v"
#vlog -64  -work fifo_generator_v13_1_0 "../../../../sim/testbanch/fifo_rqrd_example/fifo_rqrd_example.ip_user_files/ipstatic/fifo_generator_v13_1_0/hdl/fifo_generator_v13_1_rfs.v"
#vlog -64  -work fifo_generator_v13_1_0 "../../../../sim/testbanch/fifo_rqrd_example/fifo_rqrd_example.srcs/sources_1/ip/fifo_rqrd/sim/fifo_rqrd.v"

vlib msim/fifo_generator_v13_0_0
vlib msim/blk_mem_gen_v8_3_0
vlib msim/fifo_generator_v13_0_0_1

vmap fifo_generator_v13_0_0 msim/fifo_generator_v13_0_0
vmap blk_mem_gen_v8_3_0 msim/blk_mem_gen_v8_3_0
vmap fifo_generator_v13_0_0_1 msim/fifo_generator_v13_0_0_1
vmap fifo_generator_v13_0_0_2 msim/fifo_generator_v13_0_0_1

vcom -64 -93 -work fifo_generator_v13_0_0 "../../../../sim/testbanch/fifo_rqrd_example/fifo_rqrd_example.ip_user_files/ipstatic/fifo_generator_v13_0_0/simulation/fifo_generator_vhdl_beh.vhd"
vcom -64 -93 -work fifo_generator_v13_0_0 "../../../../sim/testbanch/fifo_rqrd_example/fifo_rqrd_example.ip_user_files/ipstatic/fifo_generator_v13_0_0/hdl/fifo_generator_v13_0_rfs.vhd"
vcom -64 -93 -work fifo_generator_v13_0_0 "../../../../sim/testbanch/fifo_rqrd_example/fifo_rqrd_example.srcs/sources_1/ip/fifo_rqrd/sim/fifo_rqrd.vhd"

vcom -64 -93 -work blk_mem_gen_v8_3_0 "../../../../sim/testbanch/bufo_devrd_example/bufo_devrd_example.ip_user_files/ipstatic/blk_mem_gen_v8_3_0/simulation/blk_mem_gen_v8_3.vhd"
vcom -64 -93 -work blk_mem_gen_v8_3_0 "../../../../sim/testbanch/bufo_devrd_example/bufo_devrd_example.srcs/sources_1/ip/bufo_devrd/sim/bufo_devrd.vhd"

vcom -64 -93 -work fifo_generator_v13_0_0_1 "../../../../sim/testbanch/fifo_rdpkt_out_example/fifo_rdpkt_out_example.ip_user_files/ipstatic/fifo_generator_v13_0_0/simulation/fifo_generator_vhdl_beh.vhd"
vcom -64 -93 -work fifo_generator_v13_0_0_1 "../../../../sim/testbanch/fifo_rdpkt_out_example/fifo_rdpkt_out_example.ip_user_files/ipstatic/fifo_generator_v13_0_0/hdl/fifo_generator_v13_0_rfs.vhd"
vcom -64 -93 -work fifo_generator_v13_0_0_1 "../../../../sim/testbanch/fifo_rdpkt_out_example/fifo_rdpkt_out_example.srcs/sources_1/ip/fifo_rdpkt_out/sim/fifo_rdpkt_out.vhd"

vcom -64 -93 -work fifo_generator_v13_0_0_2 "../../../../sim/testbanch/fifo_ust_ibufrx_example/fifo_ust_ibufrx_example.ip_user_files/ipstatic/fifo_generator_v13_0_0/simulation/fifo_generator_vhdl_beh.vhd"
vcom -64 -93 -work fifo_generator_v13_0_0_2 "../../../../sim/testbanch/fifo_ust_ibufrx_example/fifo_ust_ibufrx_example.ip_user_files/ipstatic/fifo_generator_v13_0_0/hdl/fifo_generator_v13_0_rfs.vhd"
vcom -64 -93 -work fifo_generator_v13_0_0_2 "../../../../sim/testbanch/fifo_ust_ibufrx_example/fifo_ust_ibufrx_example.srcs/sources_1/ip/fifo_ust_ibufrx/sim/fifo_ust_ibufrx.vhd"

vcom -64 -93 "../../../lib/reduce_pack.vhd";
vcom -64 -93 "../../../lib/vicg_common_pkg.vhd" ;
vcom -64 -93 "../../ust_def.vhd";
vcom -64 -93 "../../dev_rd.vhd"
vcom -64 -93 "../../rx_if.vhd"

#vlog -64 "../../../eth/fifo/eth_core_axi_fifo.v"
#vlog -64 "../../../eth/fifo/eth_core_fifo_ram.v"
#vlog -64 "../../../eth/eth_core_sync_block.v"
#vlog -64 "../../../eth/eth_core_sync_reset.v"

vcom -64 -93 "../testbanch/ust_rd_tb.vhd";

vsim -t 1ps -L fifo_generator_v13_0_0 -L blk_mem_gen_v8_3_0 -L fifo_generator_v13_0_0_1 -L fifo_generator_v13_0_0_2 -lib work ust_rd_tb

do ust_rd_tb_wave.do
view wave
view structure
view signals
run 4000ns

#quit -force


