######################################################################
#
# File name : eth_core_demo_tb_wave.do
# Created on: Wed Nov 04 11:57:58 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
