######################################################################
#
# File name : board_compile.do
# Created on: Tue Jun 30 14:52:18 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
file delete -force -- work
file delete -force -- msim

vlib work

#### Vivado ####
vlib msim
vlib msim/xil_defaultlib
vlib msim/fifo_generator_v12_0
vmap fifo_generator_v12_0 msim/fifo_generator_v12_0

vcom -64 -93 -work fifo_generator_v12_0 "../testbanch/fifo_eth2fg_example/fifo_eth2fg_example.srcs/sources_1/ip/fifo_eth2fg/fifo_generator_v12_0/simulation/fifo_generator_vhdl_beh.vhd"
vcom -64 -93 -work fifo_generator_v12_0 "../testbanch/fifo_eth2fg_example/fifo_eth2fg_example.srcs/sources_1/ip/fifo_eth2fg/fifo_generator_v12_0/hdl/fifo_generator_v12_0_vh_rfs.vhd"

vcom -64 -93 -work xil_defaultlib "../testbanch/fifo_eth2fg_example/fifo_eth2fg_example.srcs/sources_1/ip/fifo_eth2fg/sim/fifo_eth2fg.vhd"


vcom -64 -93 -work xil_defaultlib "../../../../../lib/common/hw/lib/vicg/vicg_common_pkg.vhd"
vcom -64 -93 -work xil_defaultlib "../../../../../lib/common/hw/lib/vicg/reduce_pack.vhd"

vcom -64 -93 -work xil_defaultlib "../testbanch/prj_cfg_sim.vhd"
vcom -64 -93 -work xil_defaultlib "../../src/prj_def.vhd"

vcom -64 -93 -work xil_defaultlib "../../src/mem_ctrl/mem_glob_pkg.vhd"
vcom -64 -93 -work xil_defaultlib "../../src/mem_ctrl/mem_wr_axi_pkg.vhd"
vcom -64 -93 -work xil_defaultlib "../../src/mem_ctrl/mem_ctrl_axi_pkg.vhd"
vcom -64 -93 -work xil_defaultlib "../../src/mem_ctrl/mem_wr_axi.vhd"

vcom -64 -93 -work xil_defaultlib "../../src/fg/fg_pkg.vhd"
vcom -64 -93 -work xil_defaultlib "../../src/fg/fgwr.vhd"
vcom -64 -93 -work xil_defaultlib "../../src/fg/fgrd.vhd"
vcom -64 -93 -work xil_defaultlib "../../src/fg/fg.vhd"

vcom -64 -93 -work xil_defaultlib "../testbanch/fgwr_tb.vhd"

vsim -t 1ps -L xil_defaultlib -L fifo_generator_v12_0 -lib xil_defaultlib xil_defaultlib.fgwr_tb


do fgwr_tb_wave.do
view wave
view structure
view signals
run 4000ns

#quit -force

