######################################################################
#
# File name : board_compile.do
# Created on: Tue Jun 30 14:52:18 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
file delete -force -- work
file delete -force -- msim

vlib work

#### Vivado ####
vlib msim
vlib msim/xil_defaultlib
vlib msim/fifo_generator_v12_0
vmap fifo_generator_v12_0 msim/fifo_generator_v12_0

vcom -64 -93 -work fifo_generator_v12_0 "../testbanch/pcie2mem_fifo_example/pcie2mem_fifo_example.srcs/sources_1/ip/pcie2mem_fifo/fifo_generator_v12_0/simulation/fifo_generator_vhdl_beh.vhd"
vcom -64 -93 -work fifo_generator_v12_0 "../testbanch/pcie2mem_fifo_example/pcie2mem_fifo_example.srcs/sources_1/ip/pcie2mem_fifo/fifo_generator_v12_0/hdl/fifo_generator_v12_0_vh_rfs.vhd"

vcom -64 -93 -work xil_defaultlib "../testbanch/pcie2mem_fifo_example/pcie2mem_fifo_example.srcs/sources_1/ip/pcie2mem_fifo/sim/pcie2mem_fifo.vhd"

vcom -64 -93 -work xil_defaultlib "../testbanch/pcie2mem_fifo_tb.vhd"

vsim -t 1ps -L xil_defaultlib -L fifo_generator_v12_0 -lib xil_defaultlib xil_defaultlib.pcie2mem_fifo_tb


##### ISE ####
#vcom -64 -93 "../../ise/core_gen/bram_dma_params.vhd"
#vcom -64 -93 "../testbanch/bram_sim.vhd"
#vlog "glbl.v"
#
#vsim -t 1ps  -lib work bram_sim


do pcie2mem_fifo_tb_wave.do
view wave
view structure
view signals
run 2500ns

#quit -force

