######################################################################
#
# File name : board_simulate.do
# Created on: Tue Jun 30 14:52:47 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -t 1ps -lib xil_defaultlib board_opt

do {usr_wave3.do}

view wave
view structure
view signals

do {board.udo}

run 1000ns
