onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /board/i
add wave -noupdate /board/sys_rst_n
add wave -noupdate /board/ep_sys_clk
add wave -noupdate /board/rp_sys_clk
add wave -noupdate /board/ep_pci_exp_txn
add wave -noupdate /board/ep_pci_exp_txp
add wave -noupdate /board/rp_pci_exp_txn
add wave -noupdate /board/rp_pci_exp_txp
add wave -noupdate /board/rp_sys_clk_n
add wave -noupdate /board/rp_sys_clk_p
add wave -noupdate /board/ep_sys_clk_n
add wave -noupdate /board/ep_sys_clk_p
add wave -noupdate /glbl/GSR
add wave -noupdate /board/EP/pci_exp_txp
add wave -noupdate /board/EP/pci_exp_txn
add wave -noupdate /board/EP/pci_exp_rxp
add wave -noupdate /board/EP/pci_exp_rxn
add wave -noupdate /board/EP/sys_clk_p
add wave -noupdate /board/EP/sys_clk_n
add wave -noupdate /board/EP/sys_rst_n
add wave -noupdate /board/EP/m_main/i_user_clk
add wave -noupdate /board/EP/m_main/i_user_reset
add wave -noupdate /board/EP/m_main/i_user_lnk_up
add wave -noupdate -divider USR_APP
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/user_clk
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/reset_n
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/rd_addr
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/rd_be
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/trn_sent
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/rd_data
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/wr_addr
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/wr_be
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/wr_data
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/wr_en
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/wr_busy
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/payload_len
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/gen_transaction
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/gen_leg_intr
add wave -noupdate /board/EP/m_main/m_ctrl/m_usr_app/gen_msi_intr
add wave -noupdate -divider pio_to_ctrl
add wave -noupdate /board/EP/m_main/m_ctrl/m_pio_to_ctrl/clk
add wave -noupdate /board/EP/m_main/m_ctrl/m_pio_to_ctrl/rst_n
add wave -noupdate /board/EP/m_main/m_ctrl/m_pio_to_ctrl/req_compl
add wave -noupdate /board/EP/m_main/m_ctrl/m_pio_to_ctrl/compl_done
add wave -noupdate /board/EP/m_main/m_ctrl/m_pio_to_ctrl/cfg_power_state_change_interrupt
add wave -noupdate /board/EP/m_main/m_ctrl/m_pio_to_ctrl/cfg_power_state_change_ack
add wave -noupdate /board/EP/m_main/m_ctrl/m_pio_to_ctrl/trn_pending
add wave -noupdate -divider RX_ENGENE
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_clk
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_rst_n
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/i_in_pkt_q
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/i_sop
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_compl
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_compl_wd
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_compl_ur
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_compl_done
add wave -noupdate -color {Slate Blue} -itemcolor Gold /board/EP/m_main/m_ctrl/m_rx/i_fsm_rx
add wave -noupdate -color {Medium Slate Blue} -itemcolor {Lime Green} -radix binary /board/EP/m_main/m_ctrl/m_rx/i_trn_type
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_m_axis_cq_tuser
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_m_axis_cq_tdata
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_m_axis_cq_tkeep
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_m_axis_cq_tvalid
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_m_axis_cq_tlast
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_m_axis_cq_tready
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_pcie_cq_np_req_count
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_pcie_cq_np_req
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_m_axis_rc_tuser
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_m_axis_rc_tdata
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_m_axis_rc_tkeep
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_m_axis_rc_tvalid
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_m_axis_rc_tlast
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_m_axis_rc_tready
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_cfg_msg_received
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_cfg_msg_received_type
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_in_cfg_msg_data
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_tc
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_attr
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_len
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_rid
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_tag
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_be
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_addr
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_at
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_des_qword0
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_des_qword1
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_des_tph_present
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_des_tph_type
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_des_tph_st_tag
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_mem_lock
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_req_mem
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_wr_addr
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_wr_be
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_wr_data
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_wr_en
add wave -noupdate /board/EP/m_main/m_ctrl/m_rx/p_out_payload_len
add wave -noupdate -divider TX_ENGENE
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/user_clk
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/reset_n
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_compl
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_compl_wd
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_compl_ur
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/payload_len
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/compl_done
add wave -noupdate -color {Slate Blue} -itemcolor Gold -radix ascii /board/EP/m_main/m_ctrl/m_tx/state_ascii
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_cc_tdata
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_cc_tkeep
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_cc_tlast
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_cc_tvalid
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_cc_tuser
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_cc_tready
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_rq_tdata
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_rq_tkeep
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_rq_tlast
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_rq_tvalid
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_rq_tuser
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_rq_tready
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/cfg_msg_transmit_done
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/cfg_msg_transmit
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/cfg_msg_transmit_type
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/cfg_msg_transmit_data
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/pcie_rq_tag
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/pcie_rq_tag_vld
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/pcie_tfc_nph_av
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/pcie_tfc_npd_av
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/pcie_tfc_np_pl_empty
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/pcie_rq_seq_num
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/pcie_rq_seq_num_vld
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/cfg_fc_ph
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/cfg_fc_nph
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/cfg_fc_cplh
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/cfg_fc_pd
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/cfg_fc_npd
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/cfg_fc_cpld
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/cfg_fc_sel
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_tc
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_td
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_ep
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_attr
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_len
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_rid
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_tag
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_be
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_addr
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_at
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/completer_id
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_des_qword0
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_des_qword1
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_des_tph_present
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_des_tph_type
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_des_tph_st_tag
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_mem_lock
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_mem
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/rd_addr
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/rd_be
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/trn_sent
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/rd_data
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/gen_transaction
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/byte_count_fbe
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/byte_count_lbe
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/lower_addr
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/lower_addr_q
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/lower_addr_qq
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/tkeep
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/tkeep_q
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/tkeep_qq
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_compl_q
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_compl_qq
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_compl_wd_q
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_compl_wd_qq
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_compl_wd_qqq
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_compl_ur_q
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/req_compl_ur_qq
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/state
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_cc_tparity
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/s_axis_rq_tparity
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/dword_count
add wave -noupdate /board/EP/m_main/m_ctrl/m_tx/rd_data_reg
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 186
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {7752886 ps}
